//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.03.29 at 02:09:33 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.training.by/tourist-vouchers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.training.tourist_vouchers.entity;
